### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Aldaviva** [Aldaviva/RemoteDesktopServicesCertificateSelector#2]
## Environment
- Windows 11 Pro
- .NET Framework 4.8.0 or 4.8.1
- Remote Desktop server is disabled in `sysdm.cpl`
- Computer's Personal and Remote Desktop certificate stores are both empty
- Active RDP certificate thumbprint in WMI is all zeroes:
    ```cmd
    > wmic /namespace:\\root\cimv2\TerminalServices PATH Win32_TSGeneralSetting Get SSLCertificateSHA1Hash
    SSLCertificateSHA1Hash
    0000000000000000000000000000000000000000
    ````

## Expected
- Program launches without crashing
- List shows 0 certificates

## Actual
1. Window is briefly shown, but the window contents (list and buttons) never render.
1. Program exits with an uncaught exception in `MainWindow.onWindowLoaded`:
    ```text
    Application: RemoteDesktopServicesCertificateSelector.exe
    Framework Version: v4.0.30319
    Description: The process was terminated due to an unhandled exception.
    Exception Info: System.ArgumentOutOfRangeException
       at System.Windows.Controls.VirtualizedCellInfoCollection.get_Item(Int32)
       at RemoteDesktopServicesCertificateSelector.Views.MainWindow.onWindowLoaded(System.Object, System.Windows.RoutedEventArgs)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
       at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
       at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
       at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
       at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
       at MS.Internal.LoadedOrUnloadedOperation.DoWork()
       at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
       at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
       at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
       at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
       at System.Windows.Media.MediaContext.Resize(System.Windows.Media.ICompositionTarget)
       at System.Windows.Interop.HwndTarget.OnResize()
       at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
       at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
       at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
    ```

**Comment by Aldaviva** [comment]
Fixed
